image: "python:3.12"

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export PYTHONPATH="$PYTHONPATH:."

stages:
  - build
  - check

build-codebase:
  stage: build
  tags:
    - docker-build
  script:
    - apt-get update -qy
    - apt-get install -y python-dev-is-python3 python3-pip

treqs-check:
  stage: check
  tags:
    - docker-build
  script:
    - pip install treqs-ng
    - treqs --version
    # - treqs list examples/famer-tim-rationale.md
    - treqs check
